### get a list of all products
GET http://localhost:3000/products

### add new product
POSt http://localhost:3000/products
Content-Type: application/json

{
  "name": "iPhone 10 Pro",
  "price": 1149
}

### to get a single product by its id
GET http://localhost:3000/products/62a5526120f64026d1c98f69

### to update a single product by its id
PATCH http://localhost:3000/products/62a5526120f64026d1c98f69
Content-Type: application/json

{
  "name": "iPhone 10",
  "price": 1799
}
### to delete a single product by its id
DELETE  http://localhost:3000/products/62a4b0bc6a2f5050a30ec4d9

### Page Not Found 404 Error Handle
GET http://localhost:3000/

### 
GET http://localhost:3000/test?name=iMac&price=2399

### 
GET http://localhost:3000/test/8766565656/iMac

###
POST http://localhost:3000/test
Content-Type: application/json

{
  "id": "8766565656",
  "name": "iMac"
}

###
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

id=8766565656&name=imac